# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import publications.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=90)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('institution', models.CharField(blank=True, max_length=256, verbose_name='Institution')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('keywords', models.CharField(max_length=256, verbose_name='Research Area')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('journal', models.CharField(blank=True, max_length=256, verbose_name='Journal')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Volume')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Issue')),
                ('pages', publications.fields.PagesField(blank=True, max_length=32)),
                ('doi', models.CharField(blank=True, max_length=128, verbose_name='DOI')),
                ('confirmed', models.BooleanField(default=False, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['-year', '-id'],
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_author', models.BooleanField(default=False, verbose_name='First Author?')),
                ('corresponding_author', models.BooleanField(default=False, verbose_name='Corresponding Author?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(editable=False, through='publications.PublicationAuthor', to='publications.Author'),
        ),
    ]
